Fix validate passwd/group logic.
Before this change, whenever I ran "apko build" I got this error:

Error: failed to build layer image: 2 errors occurred:
        * /etc/passwd file is missing: %!w(<nil>)
        * /etc/group file is missing: %!w(<nil>)

The problem is that "optional" was not true, so the code branch that
returned the wrapped error would always be followed even when err == nil.

Signed-off-by: Erik Sipsma <erik@sipsma.dev>