fix: incorrect arch tag equality detection
Given an `apko.yaml` such as the following:

```yaml
contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - ca-certificates-bundle
    - wolfi-base
    - wolfi-baselayout
    - tzdata
    - busybox
    - build-base
    - git
    - openssh
    - go-1.20

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: 0

environment:
  GODEBUG: tarinsecurepath=0,zipinsecurepath=0

entrypoint:
  command: /usr/bin/go

cmd: help

archs:
  - x86_64
  - aarch64

annotations:
  "org.opencontainers.image.authors": "PlanetScale Infra https://planetscale.com/"
  "org.opencontainers.image.url": https://github.com/planetscale/wolfi-images/tree/main/images/go
  "org.opencontainers.image.source": https://github.com/planetscale/wolfi-images/tree/main/images/go
```

And a publish command:

```console
$ apko publish --debug --package-version-tag=go-1.20 --package-version-tag-stem ./apko.yaml localhost:5000/go:1.20

...
Error: tags for arch arm64 are not identical to other arches
```

This happens even if the tags are identical between the architectures
because there will be duplicated tags in the `tagsByArch` map, eg:

```
tagsByArch: (map[types.Architecture][]string) (len=2) {
 (types.Architecture) (len=5) arm64: ([]string) (len=5 cap=8) {
  (string) (len=60) "localhost:5000/go:1.20",    # DUPE
  (string) (len=65) "localhost:5000/go:1.20.7-r1",
  (string) (len=62) "localhost:5000/go:1.20.7",
  (string) (len=60) "localhost:5000/go:1.20",    # DUPE
  (string) (len=57) "localhost:5000/go:1.
 },
 (types.Architecture) (len=5) amd64: ([]string) (len=5 cap=8) {
  (string) (len=60) "localhost:5000/go:1.20",    # DUPE
  (string) (len=65) "localhost:5000/go:1.20.7-r1",
  (string) (len=62) "localhost:5000/go:1.20.7",
  (string) (len=60) "localhost:5000/go:1.20",    # DUPE
  (string) (len=57) "localhost:5000/go:1.
 }
}
```

However the `allTagsMap` is a map and will not contain duplicated tags
and so the comparison to the 2nd architecture in `tagsByArch` will fail
the `if len(archTags) != len(allTagsMap)` check.

Fix this by tweaking the detection logic to convert each slice of tags
into a set first so that duplicated tags are flattened.

Signed-off-by: joe miller <joeym@joeym.net>